export const STARKNET_INFLUENCE_ADALIANS_CONTRACT_ADDRESS =
    process.env.STARKNET_INFLUENCE_ADALIANS_CONTRACT_ADDRESS;
if (!STARKNET_INFLUENCE_ADALIANS_CONTRACT_ADDRESS) {
    throw new Error(
        "Unable to read env variable STARKNET_INFLUENCE_ADALIANS_CONTRACT_ADDRESS",
    );
}
export let STARKNET_ADALIANS_ABI_PATH = process.env.STARKNET_ADALIANS_ABI_PATH;
if (!STARKNET_ADALIANS_ABI_PATH) {
    STARKNET_ADALIANS_ABI_PATH = "./abi/AdaliansAbi-Custom.json";
}

const MOONSTREAM_STARKNET_WEB3_PROVIDER_URI =
    process.env.MOONSTREAM_STARKNET_WEB3_PROVIDER_URI;
if (!MOONSTREAM_STARKNET_WEB3_PROVIDER_URI) {
    throw new Error(
        "Unable to read env variable MOONSTREAM_STARKNET_WEB3_PROVIDER_URI",
    );
}
const NB_CONTROLLER_ACCESS_ID = process.env.NB_CONTROLLER_ACCESS_ID;
export let MOONSTREAM_STARKNET_URI = MOONSTREAM_STARKNET_WEB3_PROVIDER_URI;
if (NB_CONTROLLER_ACCESS_ID !== "") {
    MOONSTREAM_STARKNET_URI = `${MOONSTREAM_STARKNET_WEB3_PROVIDER_URI}/${NB_CONTROLLER_ACCESS_ID}`;
    console.log(MOONSTREAM_STARKNET_URI);
}

export const MOONSTREAM_LEADERBOARD_INFLUENCE_USER_ACCESS_TOKEN =
    process.env.MOONSTREAM_LEADERBOARD_INFLUENCE_USER_ACCESS_TOKEN;

export const BLOCKS_PER_FILE = 10000;
